version: '3.1'

services:
  data_lake:
    container_name: data_lake
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    # networks:
    #   - serums
    ports:
      - "5000:5000"
    image:
      data_lake
    stdin_open: true
    tty: true
    
# networks:
#   serums:
#     external: true