version: '3.1'

services:
  data_lake:
    container_name: data_lake
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8000"
    image:
      data_lake
    stdin_open: true
    tty: true